@startuml "activity diagram"
start
:Провалидировать\nвходные параметры;
if (Входные\nпараметры\nвалидны?) then (да)
:Создать задачу и \nвернуть идентификатор \nсозданной задачи (task_id);
else (нет)
:Вернуть описание ошибки;
endif
stop
@enduml